In [ ]:
from google.colab import files
uploaded = files.upload()

### Start

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from keras.layers import Dense
from tensorflow.keras.layers import BatchNormalization
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.regularizers import l2
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.layers import Embedding, Conv1D, GlobalMaxPooling1D, Dense, Flatten
from tensorflow.keras.layers import Conv1D, GlobalMaxPooling1D, Dense, BatchNormalization, MaxPooling1D, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split


In [ ]:
df = pd.read_excel('/content/cancer patient data sets.xlsx')
df

Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0           P1   33       1              2            4             5   
1          P10   17       1              3            1             5   
2         P100   35       1              4            5             6   
3        P1000   37       1              7            7             7   
4         P101   46       1              6            8             7   
..         ...  ...     ...            ...          ...           ...   
995       P995   44       1              6            7             7   
996       P996   37       2              6            8             7   
997       P997   25       2              4            5             6   
998       P998   18       2              6            8             7   
999       P999   47       1              6            5             6   

     OccuPational Hazards  Genetic Risk  chronic Lung Disease  Balanced Diet  \
0                       4             3                     2              2   
1                       3             4                     2              2   
2                       5             5                     4              6   
3                       7             6                     7              7   
4                       7             7                     6              7   
..                    ...           ...                   ...            ...   
995                     7             7                     6              7   
996                     7             7                     6              7   
997                     5             5                     4              6   
998                     7             7                     6              7   
999                     5             5                     4              6   

     ...  Fatigue  Weight Loss  Shortness of Breath  Wheezing  \
0    ...        3            4                    2         2   
1    ...        1            3                    7         8   
2    ...        8            7                    9         2   
3    ...        4            2                    3         1   
4    ...        3            2                    4         1   
..   ...      ...          ...                  ...       ...   
995  ...        5            3                    2         7   
996  ...        9            6                    5         7   
997  ...        8            7                    9         2   
998  ...        3            2                    4         1   
999  ...        8            7                    9         2   

     Swallowing Difficulty  Clubbing of Finger Nails  Frequent Cold  \
0                        3                         1              2   
1                        6                         2              1   
2                        1                         4              6   
3                        4                         5              6   
4                        4                         2              4   
..                     ...                       ...            ...   
995                      8                         2              4   
996                      2                         4              3   
997                      1                         4              6   
998                      4                         2              4   
999                      1                         4              6   

     Dry Cough  Snoring   Level  
0            3        4     Low  
1            7        2  Medium  
2            7        2    High  
3            7        5    High  
4            2        3    High  
..         ...      ...     ...  
995          5        3    High  
996          1        4    High  
997          7        2    High  
998          2        3    High  
999          7        2    High  

[1000 rows x 25 columns]

## Data Preprocessing With StandardScaler

In [ ]:
df.shape

(1000, 25)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Patient Id                1000 non-null   object
 1   Age                       1000 non-null   int64 
 2   Gender                    1000 non-null   int64 
 3   Air Pollution             1000 non-null   int64 
 4   Alcohol use               1000 non-null   int64 
 5   Dust Allergy              1000 non-null   int64 
 6   OccuPational Hazards      1000 non-null   int64 
 7   Genetic Risk              1000 non-null   int64 
 8   chronic Lung Disease      1000 non-null   int64 
 9   Balanced Diet             1000 non-null   int64 
 10  Obesity                   1000 non-null   int64 
 11  Smoking                   1000 non-null   int64 
 12  Passive Smoker            1000 non-null   int64 
 13  Chest Pain                1000 non-null   int64 
 14  Coughing of Blood        

In [ ]:
df.isnull().sum()

Patient Id                  0
Age                         0
Gender                      0
Air Pollution               0
Alcohol use                 0
Dust Allergy                0
OccuPational Hazards        0
Genetic Risk                0
chronic Lung Disease        0
Balanced Diet               0
Obesity                     0
Smoking                     0
Passive Smoker              0
Chest Pain                  0
Coughing of Blood           0
Fatigue                     0
Weight Loss                 0
Shortness of Breath         0
Wheezing                    0
Swallowing Difficulty       0
Clubbing of Finger Nails    0
Frequent Cold               0
Dry Cough                   0
Snoring                     0
Level                       0
dtype: int64

In [ ]:
# Drop rows with null values
df.dropna(inplace=True)

# Optional: Reset the index if you want
df.reset_index(drop=True, inplace=True)


In [ ]:
df

Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0           P1   33       1              2            4             5   
1          P10   17       1              3            1             5   
2         P100   35       1              4            5             6   
3        P1000   37       1              7            7             7   
4         P101   46       1              6            8             7   
..         ...  ...     ...            ...          ...           ...   
995       P995   44       1              6            7             7   
996       P996   37       2              6            8             7   
997       P997   25       2              4            5             6   
998       P998   18       2              6            8             7   
999       P999   47       1              6            5             6   

     OccuPational Hazards  Genetic Risk  chronic Lung Disease  Balanced Diet  \
0                       4             3                     2              2   
1                       3             4                     2              2   
2                       5             5                     4              6   
3                       7             6                     7              7   
4                       7             7                     6              7   
..                    ...           ...                   ...            ...   
995                     7             7                     6              7   
996                     7             7                     6              7   
997                     5             5                     4              6   
998                     7             7                     6              7   
999                     5             5                     4              6   

     ...  Fatigue  Weight Loss  Shortness of Breath  Wheezing  \
0    ...        3            4                    2         2   
1    ...        1            3                    7         8   
2    ...        8            7                    9         2   
3    ...        4            2                    3         1   
4    ...        3            2                    4         1   
..   ...      ...          ...                  ...       ...   
995  ...        5            3                    2         7   
996  ...        9            6                    5         7   
997  ...        8            7                    9         2   
998  ...        3            2                    4         1   
999  ...        8            7                    9         2   

     Swallowing Difficulty  Clubbing of Finger Nails  Frequent Cold  \
0                        3                         1              2   
1                        6                         2              1   
2                        1                         4              6   
3                        4                         5              6   
4                        4                         2              4   
..                     ...                       ...            ...   
995                      8                         2              4   
996                      2                         4              3   
997                      1                         4              6   
998                      4                         2              4   
999                      1                         4              6   

     Dry Cough  Snoring   Level  
0            3        4     Low  
1            7        2  Medium  
2            7        2    High  
3            7        5    High  
4            2        3    High  
..         ...      ...     ...  
995          5        3    High  
996          1        4    High  
997          7        2    High  
998          2        3    High  
999          7        2    High  

[1000 rows x 25 columns]

In [ ]:
df.shape

(1000, 25)

In [ ]:
df.isnull().sum()

Patient Id                  0
Age                         0
Gender                      0
Air Pollution               0
Alcohol use                 0
Dust Allergy                0
OccuPational Hazards        0
Genetic Risk                0
chronic Lung Disease        0
Balanced Diet               0
Obesity                     0
Smoking                     0
Passive Smoker              0
Chest Pain                  0
Coughing of Blood           0
Fatigue                     0
Weight Loss                 0
Shortness of Breath         0
Wheezing                    0
Swallowing Difficulty       0
Clubbing of Finger Nails    0
Frequent Cold               0
Dry Cough                   0
Snoring                     0
Level                       0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

# Apply label encoding to each column with object dtype
for column in df.select_dtypes(include=['object']).columns:
    df[column] = label_encoder.fit_transform(df[column])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Patient Id                1000 non-null   int64
 1   Age                       1000 non-null   int64
 2   Gender                    1000 non-null   int64
 3   Air Pollution             1000 non-null   int64
 4   Alcohol use               1000 non-null   int64
 5   Dust Allergy              1000 non-null   int64
 6   OccuPational Hazards      1000 non-null   int64
 7   Genetic Risk              1000 non-null   int64
 8   chronic Lung Disease      1000 non-null   int64
 9   Balanced Diet             1000 non-null   int64
 10  Obesity                   1000 non-null   int64
 11  Smoking                   1000 non-null   int64
 12  Passive Smoker            1000 non-null   int64
 13  Chest Pain                1000 non-null   int64
 14  Coughing of Blood         1000 non-null  

In [ ]:
df

Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0             0   33       1              2            4             5   
1             1   17       1              3            1             5   
2             2   35       1              4            5             6   
3             3   37       1              7            7             7   
4             4   46       1              6            8             7   
..          ...  ...     ...            ...          ...           ...   
995         995   44       1              6            7             7   
996         996   37       2              6            8             7   
997         997   25       2              4            5             6   
998         998   18       2              6            8             7   
999         999   47       1              6            5             6   

     OccuPational Hazards  Genetic Risk  chronic Lung Disease  Balanced Diet  \
0                       4             3                     2              2   
1                       3             4                     2              2   
2                       5             5                     4              6   
3                       7             6                     7              7   
4                       7             7                     6              7   
..                    ...           ...                   ...            ...   
995                     7             7                     6              7   
996                     7             7                     6              7   
997                     5             5                     4              6   
998                     7             7                     6              7   
999                     5             5                     4              6   

     ...  Fatigue  Weight Loss  Shortness of Breath  Wheezing  \
0    ...        3            4                    2         2   
1    ...        1            3                    7         8   
2    ...        8            7                    9         2   
3    ...        4            2                    3         1   
4    ...        3            2                    4         1   
..   ...      ...          ...                  ...       ...   
995  ...        5            3                    2         7   
996  ...        9            6                    5         7   
997  ...        8            7                    9         2   
998  ...        3            2                    4         1   
999  ...        8            7                    9         2   

     Swallowing Difficulty  Clubbing of Finger Nails  Frequent Cold  \
0                        3                         1              2   
1                        6                         2              1   
2                        1                         4              6   
3                        4                         5              6   
4                        4                         2              4   
..                     ...                       ...            ...   
995                      8                         2              4   
996                      2                         4              3   
997                      1                         4              6   
998                      4                         2              4   
999                      1                         4              6   

     Dry Cough  Snoring  Level  
0            3        4      1  
1            7        2      2  
2            7        2      0  
3            7        5      0  
4            2        3      0  
..         ...      ...    ...  
995          5        3      0  
996          1        4      0  
997          7        2      0  
998          2        3      0  
999          7        2      0  

[1000 rows x 25 columns]

In [ ]:
x=df.drop(columns='Level')
y=df['Level']
y

0      1
1      2
2      0
3      0
4      0
      ..
995    0
996    0
997    0
998    0
999    0
Name: Level, Length: 1000, dtype: int64

In [ ]:
x

Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0             0   33       1              2            4             5   
1             1   17       1              3            1             5   
2             2   35       1              4            5             6   
3             3   37       1              7            7             7   
4             4   46       1              6            8             7   
..          ...  ...     ...            ...          ...           ...   
995         995   44       1              6            7             7   
996         996   37       2              6            8             7   
997         997   25       2              4            5             6   
998         998   18       2              6            8             7   
999         999   47       1              6            5             6   

     OccuPational Hazards  Genetic Risk  chronic Lung Disease  Balanced Diet  \
0                       4             3                     2              2   
1                       3             4                     2              2   
2                       5             5                     4              6   
3                       7             6                     7              7   
4                       7             7                     6              7   
..                    ...           ...                   ...            ...   
995                     7             7                     6              7   
996                     7             7                     6              7   
997                     5             5                     4              6   
998                     7             7                     6              7   
999                     5             5                     4              6   

     ...  Coughing of Blood  Fatigue  Weight Loss  Shortness of Breath  \
0    ...                  4        3            4                    2   
1    ...                  3        1            3                    7   
2    ...                  8        8            7                    9   
3    ...                  8        4            2                    3   
4    ...                  9        3            2                    4   
..   ...                ...      ...          ...                  ...   
995  ...                  7        5            3                    2   
996  ...                  7        9            6                    5   
997  ...                  8        8            7                    9   
998  ...                  9        3            2                    4   
999  ...                  8        8            7                    9   

     Wheezing  Swallowing Difficulty  Clubbing of Finger Nails  Frequent Cold  \
0           2                      3                         1              2   
1           8                      6                         2              1   
2           2                      1                         4              6   
3           1                      4                         5              6   
4           1                      4                         2              4   
..        ...                    ...                       ...            ...   
995         7                      8                         2              4   
996         7                      2                         4              3   
997         2                      1                         4              6   
998         1                      4                         2              4   
999         2                      1                         4              6   

     Dry Cough  Snoring  
0            3        4  
1            7        2  
2            7        2  
3            7        5  
4            2        3  
..         ...      ...  
995          5        3  
996          1        4  
997          7        2  
998          2        3  
999    

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3,random_state=1)

In [ ]:
from sklearn.preprocessing import StandardScaler

# Assuming you have a dataset X with shape (n_samples, n_features)
# For example, if you have xtrain and xtest datasets

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler on the training data and transform both training and test data
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.transform(xtest)

### Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
DTC = DecisionTreeClassifier()
DTC.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [ ]:
predictions = DTC.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Confusion Matrix:
[[115   0   0]
 [  0  89   0]
 [  0   0  96]]


### Decision Tree Regression

In [ ]:
from sklearn.tree import DecisionTreeRegressor
DTR = DecisionTreeRegressor()
DTR.fit(xtrain,ytrain)

DecisionTreeRegressor()

In [ ]:
predictions = DTR.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Confusion Matrix:
[[115   0   0]
 [  0  89   0]
 [  0   0  96]]


### GaussianNB

In [ ]:
from sklearn.naive_bayes import GaussianNB
GNB = GaussianNB()
GNB.fit(xtrain,ytrain)

GaussianNB()

In [ ]:
predictions = GNB.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.9233333333333333
Precision: 0.9291226215644821
Recall: 0.9233333333333333
F1 Score: 0.9232037358353148
Confusion Matrix:
[[114   0   1]
 [  3  82   4]
 [ 15   0  81]]


### BernoulliNB

In [ ]:
from sklearn.naive_bayes import BernoulliNB
BNB = BernoulliNB()
BNB.fit(xtrain,ytrain)

BernoulliNB()

In [ ]:
predictions = BNB.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.9033333333333333
Precision: 0.9082429422429421
Recall: 0.9033333333333333
F1 Score: 0.9011511047226708
Confusion Matrix:
[[114   0   1]
 [  3  83   3]
 [ 15   7  74]]


### MultinomialNB

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
xtrain_scaled = scaler.fit_transform(xtrain)
xtest_scaled = scaler.transform(xtest)
MNB = MultinomialNB()
MNB.fit(xtrain_scaled,ytrain)

MultinomialNB()

In [ ]:
predictions = MNB.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.8066666666666666
Precision: 0.8045169227416367
Recall: 0.8066666666666666
F1 Score: 0.8003593479183017
Confusion Matrix:
[[109   0   6]
 [  5  74  10]
 [ 19  18  59]]


### KNeighborsClassifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(xtrain, ytrain)
knn.score(xtrain,ytrain)
knn.score(xtest,ytest)


1.0

In [ ]:
predictions = knn.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Confusion Matrix:
[[115   0   0]
 [  0  89   0]
 [  0   0  96]]


### SVM

In [ ]:
from sklearn.svm import SVC

svmc = SVC()
svmc.fit(xtrain,ytrain)
svmc.score(xtest,ytest)


1.0

In [ ]:
predictions = svmc.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Confusion Matrix:
[[115   0   0]
 [  0  89   0]
 [  0   0  96]]


### Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier()
rf.fit(xtrain,ytrain)
rf.score(xtest,ytest)


1.0

In [ ]:
predictions = rf.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Confusion Matrix:
[[115   0   0]
 [  0  89   0]
 [  0   0  96]]


### Gredient Boost

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier()
gb.fit(xtrain,ytrain)
gb.score(xtest,ytest)


1.0

In [ ]:
predictions = gb.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Confusion Matrix:
[[115   0   0]
 [  0  89   0]
 [  0   0  96]]


## Data Preprocessing With MinMaxScaler

In [ ]:
df.shape

(1000, 25)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Patient Id                1000 non-null   object
 1   Age                       1000 non-null   int64 
 2   Gender                    1000 non-null   int64 
 3   Air Pollution             1000 non-null   int64 
 4   Alcohol use               1000 non-null   int64 
 5   Dust Allergy              1000 non-null   int64 
 6   OccuPational Hazards      1000 non-null   int64 
 7   Genetic Risk              1000 non-null   int64 
 8   chronic Lung Disease      1000 non-null   int64 
 9   Balanced Diet             1000 non-null   int64 
 10  Obesity                   1000 non-null   int64 
 11  Smoking                   1000 non-null   int64 
 12  Passive Smoker            1000 non-null   int64 
 13  Chest Pain                1000 non-null   int64 
 14  Coughing of Blood        

In [ ]:
df.isnull().sum()

Patient Id                  0
Age                         0
Gender                      0
Air Pollution               0
Alcohol use                 0
Dust Allergy                0
OccuPational Hazards        0
Genetic Risk                0
chronic Lung Disease        0
Balanced Diet               0
Obesity                     0
Smoking                     0
Passive Smoker              0
Chest Pain                  0
Coughing of Blood           0
Fatigue                     0
Weight Loss                 0
Shortness of Breath         0
Wheezing                    0
Swallowing Difficulty       0
Clubbing of Finger Nails    0
Frequent Cold               0
Dry Cough                   0
Snoring                     0
Level                       0
dtype: int64

In [ ]:
# Drop rows with null values
df.dropna(inplace=True)

# Optional: Reset the index if you want
df.reset_index(drop=True, inplace=True)


In [ ]:
df

Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0           P1   33       1              2            4             5   
1          P10   17       1              3            1             5   
2         P100   35       1              4            5             6   
3        P1000   37       1              7            7             7   
4         P101   46       1              6            8             7   
..         ...  ...     ...            ...          ...           ...   
995       P995   44       1              6            7             7   
996       P996   37       2              6            8             7   
997       P997   25       2              4            5             6   
998       P998   18       2              6            8             7   
999       P999   47       1              6            5             6   

     OccuPational Hazards  Genetic Risk  chronic Lung Disease  Balanced Diet  \
0                       4             3                     2              2   
1                       3             4                     2              2   
2                       5             5                     4              6   
3                       7             6                     7              7   
4                       7             7                     6              7   
..                    ...           ...                   ...            ...   
995                     7             7                     6              7   
996                     7             7                     6              7   
997                     5             5                     4              6   
998                     7             7                     6              7   
999                     5             5                     4              6   

     ...  Fatigue  Weight Loss  Shortness of Breath  Wheezing  \
0    ...        3            4                    2         2   
1    ...        1            3                    7         8   
2    ...        8            7                    9         2   
3    ...        4            2                    3         1   
4    ...        3            2                    4         1   
..   ...      ...          ...                  ...       ...   
995  ...        5            3                    2         7   
996  ...        9            6                    5         7   
997  ...        8            7                    9         2   
998  ...        3            2                    4         1   
999  ...        8            7                    9         2   

     Swallowing Difficulty  Clubbing of Finger Nails  Frequent Cold  \
0                        3                         1              2   
1                        6                         2              1   
2                        1                         4              6   
3                        4                         5              6   
4                        4                         2              4   
..                     ...                       ...            ...   
995                      8                         2              4   
996                      2                         4              3   
997                      1                         4              6   
998                      4                         2              4   
999                      1                         4              6   

     Dry Cough  Snoring   Level  
0            3        4     Low  
1            7        2  Medium  
2            7        2    High  
3            7        5    High  
4            2        3    High  
..         ...      ...     ...  
995          5        3    High  
996          1        4    High  
997          7        2    High  
998          2        3    High  
999          7        2    High  

[1000 rows x 25 columns]

In [ ]:
df.shape

(1000, 25)

In [ ]:
df.isnull().sum()

Patient Id                  0
Age                         0
Gender                      0
Air Pollution               0
Alcohol use                 0
Dust Allergy                0
OccuPational Hazards        0
Genetic Risk                0
chronic Lung Disease        0
Balanced Diet               0
Obesity                     0
Smoking                     0
Passive Smoker              0
Chest Pain                  0
Coughing of Blood           0
Fatigue                     0
Weight Loss                 0
Shortness of Breath         0
Wheezing                    0
Swallowing Difficulty       0
Clubbing of Finger Nails    0
Frequent Cold               0
Dry Cough                   0
Snoring                     0
Level                       0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

# Apply label encoding to each column with object dtype
for column in df.select_dtypes(include=['object']).columns:
    df[column] = label_encoder.fit_transform(df[column])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Patient Id                1000 non-null   int64
 1   Age                       1000 non-null   int64
 2   Gender                    1000 non-null   int64
 3   Air Pollution             1000 non-null   int64
 4   Alcohol use               1000 non-null   int64
 5   Dust Allergy              1000 non-null   int64
 6   OccuPational Hazards      1000 non-null   int64
 7   Genetic Risk              1000 non-null   int64
 8   chronic Lung Disease      1000 non-null   int64
 9   Balanced Diet             1000 non-null   int64
 10  Obesity                   1000 non-null   int64
 11  Smoking                   1000 non-null   int64
 12  Passive Smoker            1000 non-null   int64
 13  Chest Pain                1000 non-null   int64
 14  Coughing of Blood         1000 non-null  

In [ ]:
df

Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0             0   33       1              2            4             5   
1             1   17       1              3            1             5   
2             2   35       1              4            5             6   
3             3   37       1              7            7             7   
4             4   46       1              6            8             7   
..          ...  ...     ...            ...          ...           ...   
995         995   44       1              6            7             7   
996         996   37       2              6            8             7   
997         997   25       2              4            5             6   
998         998   18       2              6            8             7   
999         999   47       1              6            5             6   

     OccuPational Hazards  Genetic Risk  chronic Lung Disease  Balanced Diet  \
0                       4             3                     2              2   
1                       3             4                     2              2   
2                       5             5                     4              6   
3                       7             6                     7              7   
4                       7             7                     6              7   
..                    ...           ...                   ...            ...   
995                     7             7                     6              7   
996                     7             7                     6              7   
997                     5             5                     4              6   
998                     7             7                     6              7   
999                     5             5                     4              6   

     ...  Fatigue  Weight Loss  Shortness of Breath  Wheezing  \
0    ...        3            4                    2         2   
1    ...        1            3                    7         8   
2    ...        8            7                    9         2   
3    ...        4            2                    3         1   
4    ...        3            2                    4         1   
..   ...      ...          ...                  ...       ...   
995  ...        5            3                    2         7   
996  ...        9            6                    5         7   
997  ...        8            7                    9         2   
998  ...        3            2                    4         1   
999  ...        8            7                    9         2   

     Swallowing Difficulty  Clubbing of Finger Nails  Frequent Cold  \
0                        3                         1              2   
1                        6                         2              1   
2                        1                         4              6   
3                        4                         5              6   
4                        4                         2              4   
..                     ...                       ...            ...   
995                      8                         2              4   
996                      2                         4              3   
997                      1                         4              6   
998                      4                         2              4   
999                      1                         4              6   

     Dry Cough  Snoring  Level  
0            3        4      1  
1            7        2      2  
2            7        2      0  
3            7        5      0  
4            2        3      0  
..         ...      ...    ...  
995          5        3      0  
996          1        4      0  
997          7        2      0  
998          2        3      0  
999          7        2      0  

[1000 rows x 25 columns]

In [ ]:
x=df.drop(columns='Level')
y=df['Level']
y

0      1
1      2
2      0
3      0
4      0
      ..
995    0
996    0
997    0
998    0
999    0
Name: Level, Length: 1000, dtype: int64

In [ ]:
x

Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0             0   33       1              2            4             5   
1             1   17       1              3            1             5   
2             2   35       1              4            5             6   
3             3   37       1              7            7             7   
4             4   46       1              6            8             7   
..          ...  ...     ...            ...          ...           ...   
995         995   44       1              6            7             7   
996         996   37       2              6            8             7   
997         997   25       2              4            5             6   
998         998   18       2              6            8             7   
999         999   47       1              6            5             6   

     OccuPational Hazards  Genetic Risk  chronic Lung Disease  Balanced Diet  \
0                       4             3                     2              2   
1                       3             4                     2              2   
2                       5             5                     4              6   
3                       7             6                     7              7   
4                       7             7                     6              7   
..                    ...           ...                   ...            ...   
995                     7             7                     6              7   
996                     7             7                     6              7   
997                     5             5                     4              6   
998                     7             7                     6              7   
999                     5             5                     4              6   

     ...  Coughing of Blood  Fatigue  Weight Loss  Shortness of Breath  \
0    ...                  4        3            4                    2   
1    ...                  3        1            3                    7   
2    ...                  8        8            7                    9   
3    ...                  8        4            2                    3   
4    ...                  9        3            2                    4   
..   ...                ...      ...          ...                  ...   
995  ...                  7        5            3                    2   
996  ...                  7        9            6                    5   
997  ...                  8        8            7                    9   
998  ...                  9        3            2                    4   
999  ...                  8        8            7                    9   

     Wheezing  Swallowing Difficulty  Clubbing of Finger Nails  Frequent Cold  \
0           2                      3                         1              2   
1           8                      6                         2              1   
2           2                      1                         4              6   
3           1                      4                         5              6   
4           1                      4                         2              4   
..        ...                    ...                       ...            ...   
995         7                      8                         2              4   
996         7                      2                         4              3   
997         2                      1                         4              6   
998         1                      4                         2              4   
999         2                      1                         4              6   

     Dry Cough  Snoring  
0            3        4  
1            7        2  
2            7        2  
3            7        5  
4            2        3  
..         ...      ...  
995          5        3  
996          1        4  
997          7        2  
998          2        3  
999    

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3,random_state=1)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

# Assuming you have a dataset X with shape (n_samples, n_features)
# For example, if you have xtrain and xtest datasets

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Fit the scaler on the training data and transform both training and test data
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.transform(xtest)

In [ ]:
xtrain[0]

array([0.73173173, 0.50847458, 0.        , 0.14285714, 0.        ,
       0.57142857, 0.28571429, 0.16666667, 0.33333333, 0.16666667,
       0.5       , 0.        , 0.42857143, 0.125     , 0.375     ,
       0.625     , 0.85714286, 0.125     , 0.57142857, 1.        ,
       0.        , 0.33333333, 0.16666667, 0.33333333])

### Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
DTC = DecisionTreeClassifier()
DTC.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [ ]:
predictions = DTC.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Confusion Matrix:
[[115   0   0]
 [  0  89   0]
 [  0   0  96]]


### Decision Tree Regression

In [ ]:
from sklearn.tree import DecisionTreeRegressor
DTR = DecisionTreeRegressor()
DTR.fit(xtrain,ytrain)

DecisionTreeRegressor()

In [ ]:
predictions = DTR.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Confusion Matrix:
[[115   0   0]
 [  0  89   0]
 [  0   0  96]]


### GaussianNB

In [ ]:
from sklearn.naive_bayes import GaussianNB
GNB = GaussianNB()
GNB.fit(xtrain,ytrain)

GaussianNB()

In [ ]:
predictions = GNB.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.9233333333333333
Precision: 0.9291226215644821
Recall: 0.9233333333333333
F1 Score: 0.9232037358353148
Confusion Matrix:
[[114   0   1]
 [  3  82   4]
 [ 15   0  81]]


### BernoulliNB

In [ ]:
from sklearn.naive_bayes import BernoulliNB
BNB = BernoulliNB()
BNB.fit(xtrain,ytrain)

BernoulliNB()

In [ ]:
predictions = BNB.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.8366666666666667
Precision: 0.8528982679289826
Recall: 0.8366666666666667
F1 Score: 0.8338941252890559
Confusion Matrix:
[[115   0   0]
 [  0  62  27]
 [ 22   0  74]]


### MultinomialNB

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
xtrain_scaled = scaler.fit_transform(xtrain)
xtest_scaled = scaler.transform(xtest)
MNB = MultinomialNB()
MNB.fit(xtrain_scaled,ytrain)

MultinomialNB()

In [ ]:
predictions = MNB.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.76
Precision: 0.760010740703212
Recall: 0.76
F1 Score: 0.7541334455168911
Confusion Matrix:
[[108   0   7]
 [ 12  57  20]
 [ 19  14  63]]


### KNeighborsClassifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(xtrain, ytrain)
knn.score(xtrain,ytrain)
knn.score(xtest,ytest)


1.0

In [ ]:
predictions = knn.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Confusion Matrix:
[[115   0   0]
 [  0  89   0]
 [  0   0  96]]


### SVM

In [ ]:
from sklearn.svm import SVC

svmc = SVC()
svmc.fit(xtrain,ytrain)
svmc.score(xtest,ytest)


1.0

In [ ]:
predictions = svmc.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Confusion Matrix:
[[115   0   0]
 [  0  89   0]
 [  0   0  96]]


### Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier()
rf.fit(xtrain,ytrain)
rf.score(xtest,ytest)


1.0

In [ ]:
predictions = rf.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Confusion Matrix:
[[115   0   0]
 [  0  89   0]
 [  0   0  96]]


### Gredient Boost

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier()
gb.fit(xtrain,ytrain)
gb.score(xtest,ytest)


1.0

In [ ]:
predictions = gb.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Confusion Matrix:
[[115   0   0]
 [  0  89   0]
 [  0   0  96]]


## Data Preprocessing Without Normalization

In [ ]:
df.shape

(1000, 25)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Patient Id                1000 non-null   int64
 1   Age                       1000 non-null   int64
 2   Gender                    1000 non-null   int64
 3   Air Pollution             1000 non-null   int64
 4   Alcohol use               1000 non-null   int64
 5   Dust Allergy              1000 non-null   int64
 6   OccuPational Hazards      1000 non-null   int64
 7   Genetic Risk              1000 non-null   int64
 8   chronic Lung Disease      1000 non-null   int64
 9   Balanced Diet             1000 non-null   int64
 10  Obesity                   1000 non-null   int64
 11  Smoking                   1000 non-null   int64
 12  Passive Smoker            1000 non-null   int64
 13  Chest Pain                1000 non-null   int64
 14  Coughing of Blood         1000 non-null  

In [ ]:
df.isnull().sum()

Patient Id                  0
Age                         0
Gender                      0
Air Pollution               0
Alcohol use                 0
Dust Allergy                0
OccuPational Hazards        0
Genetic Risk                0
chronic Lung Disease        0
Balanced Diet               0
Obesity                     0
Smoking                     0
Passive Smoker              0
Chest Pain                  0
Coughing of Blood           0
Fatigue                     0
Weight Loss                 0
Shortness of Breath         0
Wheezing                    0
Swallowing Difficulty       0
Clubbing of Finger Nails    0
Frequent Cold               0
Dry Cough                   0
Snoring                     0
Level                       0
dtype: int64

In [ ]:
# Drop rows with null values
df.dropna(inplace=True)

# Optional: Reset the index if you want
df.reset_index(drop=True, inplace=True)


In [ ]:
df

Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0             0   33       1              2            4             5   
1             1   17       1              3            1             5   
2             2   35       1              4            5             6   
3             3   37       1              7            7             7   
4             4   46       1              6            8             7   
..          ...  ...     ...            ...          ...           ...   
995         995   44       1              6            7             7   
996         996   37       2              6            8             7   
997         997   25       2              4            5             6   
998         998   18       2              6            8             7   
999         999   47       1              6            5             6   

     OccuPational Hazards  Genetic Risk  chronic Lung Disease  Balanced Diet  \
0                       4             3                     2              2   
1                       3             4                     2              2   
2                       5             5                     4              6   
3                       7             6                     7              7   
4                       7             7                     6              7   
..                    ...           ...                   ...            ...   
995                     7             7                     6              7   
996                     7             7                     6              7   
997                     5             5                     4              6   
998                     7             7                     6              7   
999                     5             5                     4              6   

     ...  Fatigue  Weight Loss  Shortness of Breath  Wheezing  \
0    ...        3            4                    2         2   
1    ...        1            3                    7         8   
2    ...        8            7                    9         2   
3    ...        4            2                    3         1   
4    ...        3            2                    4         1   
..   ...      ...          ...                  ...       ...   
995  ...        5            3                    2         7   
996  ...        9            6                    5         7   
997  ...        8            7                    9         2   
998  ...        3            2                    4         1   
999  ...        8            7                    9         2   

     Swallowing Difficulty  Clubbing of Finger Nails  Frequent Cold  \
0                        3                         1              2   
1                        6                         2              1   
2                        1                         4              6   
3                        4                         5              6   
4                        4                         2              4   
..                     ...                       ...            ...   
995                      8                         2              4   
996                      2                         4              3   
997                      1                         4              6   
998                      4                         2              4   
999                      1                         4              6   

     Dry Cough  Snoring  Level  
0            3        4      1  
1            7        2      2  
2            7        2      0  
3            7        5      0  
4            2        3      0  
..         ...      ...    ...  
995          5        3      0  
996          1        4      0  
997          7        2      0  
998          2        3      0  
999          7        2      0  

[1000 rows x 25 columns]

In [ ]:
df.shape

(1000, 25)

In [ ]:
df.isnull().sum()

Patient Id                  0
Age                         0
Gender                      0
Air Pollution               0
Alcohol use                 0
Dust Allergy                0
OccuPational Hazards        0
Genetic Risk                0
chronic Lung Disease        0
Balanced Diet               0
Obesity                     0
Smoking                     0
Passive Smoker              0
Chest Pain                  0
Coughing of Blood           0
Fatigue                     0
Weight Loss                 0
Shortness of Breath         0
Wheezing                    0
Swallowing Difficulty       0
Clubbing of Finger Nails    0
Frequent Cold               0
Dry Cough                   0
Snoring                     0
Level                       0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

# Apply label encoding to each column with object dtype
for column in df.select_dtypes(include=['object']).columns:
    df[column] = label_encoder.fit_transform(df[column])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Patient Id                1000 non-null   int64
 1   Age                       1000 non-null   int64
 2   Gender                    1000 non-null   int64
 3   Air Pollution             1000 non-null   int64
 4   Alcohol use               1000 non-null   int64
 5   Dust Allergy              1000 non-null   int64
 6   OccuPational Hazards      1000 non-null   int64
 7   Genetic Risk              1000 non-null   int64
 8   chronic Lung Disease      1000 non-null   int64
 9   Balanced Diet             1000 non-null   int64
 10  Obesity                   1000 non-null   int64
 11  Smoking                   1000 non-null   int64
 12  Passive Smoker            1000 non-null   int64
 13  Chest Pain                1000 non-null   int64
 14  Coughing of Blood         1000 non-null  

In [ ]:
df

Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0             0   33       1              2            4             5   
1             1   17       1              3            1             5   
2             2   35       1              4            5             6   
3             3   37       1              7            7             7   
4             4   46       1              6            8             7   
..          ...  ...     ...            ...          ...           ...   
995         995   44       1              6            7             7   
996         996   37       2              6            8             7   
997         997   25       2              4            5             6   
998         998   18       2              6            8             7   
999         999   47       1              6            5             6   

     OccuPational Hazards  Genetic Risk  chronic Lung Disease  Balanced Diet  \
0                       4             3                     2              2   
1                       3             4                     2              2   
2                       5             5                     4              6   
3                       7             6                     7              7   
4                       7             7                     6              7   
..                    ...           ...                   ...            ...   
995                     7             7                     6              7   
996                     7             7                     6              7   
997                     5             5                     4              6   
998                     7             7                     6              7   
999                     5             5                     4              6   

     ...  Fatigue  Weight Loss  Shortness of Breath  Wheezing  \
0    ...        3            4                    2         2   
1    ...        1            3                    7         8   
2    ...        8            7                    9         2   
3    ...        4            2                    3         1   
4    ...        3            2                    4         1   
..   ...      ...          ...                  ...       ...   
995  ...        5            3                    2         7   
996  ...        9            6                    5         7   
997  ...        8            7                    9         2   
998  ...        3            2                    4         1   
999  ...        8            7                    9         2   

     Swallowing Difficulty  Clubbing of Finger Nails  Frequent Cold  \
0                        3                         1              2   
1                        6                         2              1   
2                        1                         4              6   
3                        4                         5              6   
4                        4                         2              4   
..                     ...                       ...            ...   
995                      8                         2              4   
996                      2                         4              3   
997                      1                         4              6   
998                      4                         2              4   
999                      1                         4              6   

     Dry Cough  Snoring  Level  
0            3        4      1  
1            7        2      2  
2            7        2      0  
3            7        5      0  
4            2        3      0  
..         ...      ...    ...  
995          5        3      0  
996          1        4      0  
997          7        2      0  
998          2        3      0  
999          7        2      0  

[1000 rows x 25 columns]

In [ ]:
x=df.drop(columns='Level')
y=df['Level']
y

0      1
1      2
2      0
3      0
4      0
      ..
995    0
996    0
997    0
998    0
999    0
Name: Level, Length: 1000, dtype: int64

In [ ]:
x

Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0             0   33       1              2            4             5   
1             1   17       1              3            1             5   
2             2   35       1              4            5             6   
3             3   37       1              7            7             7   
4             4   46       1              6            8             7   
..          ...  ...     ...            ...          ...           ...   
995         995   44       1              6            7             7   
996         996   37       2              6            8             7   
997         997   25       2              4            5             6   
998         998   18       2              6            8             7   
999         999   47       1              6            5             6   

     OccuPational Hazards  Genetic Risk  chronic Lung Disease  Balanced Diet  \
0                       4             3                     2              2   
1                       3             4                     2              2   
2                       5             5                     4              6   
3                       7             6                     7              7   
4                       7             7                     6              7   
..                    ...           ...                   ...            ...   
995                     7             7                     6              7   
996                     7             7                     6              7   
997                     5             5                     4              6   
998                     7             7                     6              7   
999                     5             5                     4              6   

     ...  Coughing of Blood  Fatigue  Weight Loss  Shortness of Breath  \
0    ...                  4        3            4                    2   
1    ...                  3        1            3                    7   
2    ...                  8        8            7                    9   
3    ...                  8        4            2                    3   
4    ...                  9        3            2                    4   
..   ...                ...      ...          ...                  ...   
995  ...                  7        5            3                    2   
996  ...                  7        9            6                    5   
997  ...                  8        8            7                    9   
998  ...                  9        3            2                    4   
999  ...                  8        8            7                    9   

     Wheezing  Swallowing Difficulty  Clubbing of Finger Nails  Frequent Cold  \
0           2                      3                         1              2   
1           8                      6                         2              1   
2           2                      1                         4              6   
3           1                      4                         5              6   
4           1                      4                         2              4   
..        ...                    ...                       ...            ...   
995         7                      8                         2              4   
996         7                      2                         4              3   
997         2                      1                         4              6   
998         1                      4                         2              4   
999         2                      1                         4              6   

     Dry Cough  Snoring  
0            3        4  
1            7        2  
2            7        2  
3            7        5  
4            2        3  
..         ...      ...  
995          5        3  
996          1        4  
997          7        2  
998          2        3  
999    

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3,random_state=1)

In [ ]:
xtrain

Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
731         731   44       1              2            1             5   
716         716   18       2              3            2             1   
640         640   38       2              1            2             3   
804         804   19       1              3            2             4   
737         737   62       1              6            8             7   
..          ...  ...     ...            ...          ...           ...   
767         767   35       2              4            5             6   
72           72   38       2              2            1             5   
908         908   24       1              6            8             7   
235         235   45       2              1            2             4   
37           37   28       1              6            7             8   

     OccuPational Hazards  Genetic Risk  chronic Lung Disease  Balanced Diet  \
731                     3             2                     3              2   
716                     3             2                     1              3   
640                     4             2                     4              3   
804                     2             3                     2              3   
737                     7             7                     6              2   
..                    ...           ...                   ...            ...   
767                     5             5                     4              6   
72                      3             2                     3              2   
908                     7             6                     7              7   
235                     5             6                     5              5   
37                      7             6                     7              7   

     ...  Coughing of Blood  Fatigue  Weight Loss  Shortness of Breath  \
731  ...                  4        6            7                    2   
716  ...                  2        2            2                    1   
640  ...                  4        4            1                    2   
804  ...                  3        4            5                    6   
737  ...                  3        2            7                    6   
..   ...                ...      ...          ...                  ...   
767  ...                  8        8            7                    9   
72   ...                  4        6            7                    2   
908  ...                  6        5            2                    5   
235  ...                  2        3            8                    7   
37   ...                  8        2            3                    6   

     Wheezing  Swallowing Difficulty  Clubbing of Finger Nails  Frequent Cold  \
731         5                      8                         1              3   
716         3                      4                         4              1   
640         4                      6                         5              4   
804         5                      5                         4              6   
737         5                      1                         9              3   
..        ...                    ...                       ...            ...   
767         2                      1                         4              6   
72          5                      8                         1              3   
908         2                      3                         2              1   
235         3                      8                         3              2   
37          4                      2                         3              1   

     Dry Cough  Snoring  
731          2        3  
716          4        1  
640          2        5  
804          5        4  
737          4        2  
..         ...      ...  
767          7        2  
72           2        3  
908          7        6  
235          3        1  
37     

### Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
DTC = DecisionTreeClassifier()
DTC.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [ ]:
predictions = DTC.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Confusion Matrix:
[[115   0   0]
 [  0  89   0]
 [  0   0  96]]


### Decision Tree Regression

In [ ]:
from sklearn.tree import DecisionTreeRegressor
DTR = DecisionTreeRegressor()
DTR.fit(xtrain,ytrain)

DecisionTreeRegressor()

In [ ]:
predictions = DTR.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Confusion Matrix:
[[115   0   0]
 [  0  89   0]
 [  0   0  96]]


### GaussianNB

In [ ]:
from sklearn.naive_bayes import GaussianNB
GNB = GaussianNB()
GNB.fit(xtrain,ytrain)

GaussianNB()

In [ ]:
predictions = GNB.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.9233333333333333
Precision: 0.9291226215644821
Recall: 0.9233333333333333
F1 Score: 0.9232037358353148
Confusion Matrix:
[[114   0   1]
 [  3  82   4]
 [ 15   0  81]]


### BernoulliNB

In [ ]:
from sklearn.naive_bayes import BernoulliNB
BNB = BernoulliNB()
BNB.fit(xtrain,ytrain)

BernoulliNB()

In [ ]:
predictions = BNB.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.38333333333333336
Precision: 0.14694444444444446
Recall: 0.38333333333333336
F1 Score: 0.21244979919678714
Confusion Matrix:
[[115   0   0]
 [ 89   0   0]
 [ 96   0   0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### MultinomialNB

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
xtrain_scaled = scaler.fit_transform(xtrain)
xtest_scaled = scaler.transform(xtest)
MNB = MultinomialNB()
MNB.fit(xtrain_scaled,ytrain)

MultinomialNB()

In [ ]:
predictions = MNB.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.2966666666666667
Precision: 0.08830546265328874
Recall: 0.2966666666666667
F1 Score: 0.13609965635738833
Confusion Matrix:
[[  0 114   1]
 [  0  89   0]
 [  0  96   0]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but MultinomialNB was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### KNeighborsClassifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(xtrain, ytrain)
knn.score(xtrain,ytrain)
knn.score(xtest,ytest)


0.7866666666666666

In [ ]:
predictions = knn.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.7866666666666666
Precision: 0.7882302514307159
Recall: 0.7866666666666666
F1 Score: 0.7820477595595806
Confusion Matrix:
[[106   3   6]
 [ 11  69   9]
 [ 19  16  61]]


### SVM

In [ ]:
from sklearn.svm import SVC

svmc = SVC()
svmc.fit(xtrain,ytrain)
svmc.score(xtest,ytest)


0.34

In [ ]:
predictions = svmc.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.34
Precision: 0.23975
Recall: 0.34
F1 Score: 0.28117103235747304
Confusion Matrix:
[[60  0 55]
 [46  0 43]
 [54  0 42]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier()
rf.fit(xtrain,ytrain)
rf.score(xtest,ytest)


1.0

In [ ]:
predictions = rf.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Confusion Matrix:
[[115   0   0]
 [  0  89   0]
 [  0   0  96]]


### Gredient Boost

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier()
gb.fit(xtrain,ytrain)
gb.score(xtest,ytest)


1.0

In [ ]:
predictions = gb.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
precision = precision_score(ytest, predictions, average='weighted')
recall = recall_score(ytest, predictions, average='weighted')
f1 = f1_score(ytest, predictions, average='weighted')
conf_matrix = confusion_matrix(ytest, predictions)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Confusion Matrix:
[[115   0   0]
 [  0  89   0]
 [  0   0  96]]
